name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the Release'
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies

      - uses: eskatos/gradle-command-action@v1
        name: Assemble
        with:
          arguments: assemble

      - uses: eskatos/gradle-command-action@v1
        name: Tests
        with:
          arguments: >
            test
            -Pdatalbry.github.secret=${{ secrets.GIT_HUB_SECRET }}
            -Pdatalbry.github.uri=${{ secrets.GIT_HUB_URI }}

  Release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.version != '' }}
    needs: Build

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - id: install-secret-key
        name: Install GnuPG Key
        run: |
          cat <(echo -e "${{ secrets.GNUPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - uses: eskatos/gradle-command-action@v1
        name: Set Release Version
        with:
          arguments: >
            writeVersion
            -PprojectVersion=${{ github.event.inputs.version }}

      - uses: eskatos/gradle-command-action@v1
        name: Release to staging
        with:
          arguments: >
            publishMavenPublicationToSonatypeRepository
            closeAndReleaseSonatypeStagingRepository
            -Pdatalbry.github.secret=${{ secrets.GIT_HUB_SECRET }}
            -Pdatalbry.github.uri=${{ secrets.GIT_HUB_URI }}
            -PprojectVersion=${{ github.event.inputs.version }}
            -PsonatypeUsername=${{ secrets.MAVENCENTRALUSERNAME }}
            -PsonatypePassword=${{ secrets.MAVENCENTRALPASSWORD }}
            -Psigning.gnupg.keyName=${{ secrets.GNUPG_SECRET_NAME }}
            -Psigning.gnupg.passphrase=${{ secrets.GNUPG_SECRET_PASSWORD }}

      - uses: EndBug/add-and-commit@v7
        name: Commit Version
        with:
          add: 'gradle.properties'
          message: '[CI] Release Version ${{ github.event.inputs.version }}'
          tag: 'v${{ github.event.inputs.version  }}'


